function [fitresult, gof] = createFit_f(xx, yy, zz)
%CREATEFIT(XX,YY,ZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Input : yy
%      Z Output: zz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-May-2022 17:17:47


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xx, yy, zz );

% Set up fittype and options.
ft = fittype( 'poly11' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'fitted_aberration' );
% h = plot( fitresult, [xData, yData], zData );
% % legend( h, 'fitted_aberration_curve', 'zz vs. xx, yy', 'Location', 'NorthEast', 'Interpreter', 'none' );
% 
% % Label axes
% xlabel( 'X direction (pixels)', 'Interpreter', 'none' );
% ylabel( 'Y direction (pixels)', 'Interpreter', 'none' );
% zlabel( 'Delta in Y direction (pixels)', 'Interpreter', 'none' );
% grid off
% 
% view( [-1 -1 1]);
% view(210,30);
% set(gca,'FontName','Arial','FontSize',12);

