function [fitresult, gof] = createFitx(xx, yy, zz)
%CREATEFIT(XX,YY,ZZ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Input : yy
%      Z Output: zz
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-May-2022 17:17:47


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xx, yy, zz );

% Set up fittype and options.
ft = fittype( 'poly22' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Set default axes font size
%set(0, 'DefaultAxesFontSize', 14);

% Plot fit with data.
figure( 'Name', 'fitted_aberration' );
h = plot( fitresult, [xData, yData], zData);
dataPointsHandle = findobj(h, 'Type', 'scatter'); % Find scatter data objects
if ~isempty(dataPointsHandle)
    set(dataPointsHandle, 'SizeData', 100, 'Marker', 'o'); 
end
% legend( h, 'fitted_aberration_curve', 'zz vs. xx, yy', 'Location', 'NorthEast', 'Interpreter', 'none' );

% Label axes
%xlabel( 'X direction', 'Interpreter', 'none' );
%ylabel( 'Y direction', 'Interpreter', 'none' );
%zlabel( 'Displacement', 'Interpreter', 'none' );
grid off

view( [-1 -1 1]);
view(210,30);
set(gca,'FontName','Arial','FontSize',21);

